### PR TITLE
json body at login as per fineract-726

### PR DESCRIPTION
**Pull request by francisguchie**
Thank you for contributing to Mifos web self-service.

##Description
https://github.com/openMF/web-self-service-app/issues/180 

##Related issues and discussion
#180 

##Screenshots/GIFs, if any:

### CODE REVIEW

**Comment by francisguchie** [comment]
@rrpawar96 @pete10200 
I have tested this more than once and it works fine on the latest builds - who will merge??

**Comment by rrpawar96** [comment]
@francisguchie  I have created a new PR  https://github.com/openMF/web-self-service-app/pull/183, 

now, where it will also resolve more issues than login like redirecting the page to the dashboard after login,

and also the new PR will resolve the issue where it was refreshing data in multiple tabs when we used to refresh only one tab

Just we will need someone new to merge

**Comment by denomon** [comment]
@francisguchie Can this pls be merged in as develop if failing the PR pending.

**Comment by francisguchie** [comment]
> @francisguchie Can this pls be merged in as develop if failing the PR pending.

@denomon , I think i have not rights to merge.

**Comment by francisguchie** [comment]
This issues has taken another twist

**Pull request closed without merging**
