### PR TITLE
Unsuccesful login message

### PR DESCRIPTION
**Pull request by TechnicaVoyage**
Whenever login is unsuccessful due to any reason, a corresponding message is shown in red text.
For eg: If the server takes too long to respond (timeout), a message with corresponding code and text will appear above the login button.

screenshot 88

Affected urls:
/login

### CODE REVIEW

**Comment by TechnicaVoyage** [comment]
@dhruvdutt I preferred a descriptive message over a technical one (for the sake of clients' clarity).
But on second thoughts, `defaultUserMessage` can be modified for better clarity, so I'm editing the code to use `httpStatusCode` and `defultUserMessage`.

screenshot 90

Should I squash the commits or is there's anything to improve?

**Comment by TechnicaVoyage** [comment]
@dhruvdutt I agree, so I removed `httpStatusCode` and logged `developerMessage` in the developer console.

screenshot 91

Should I commit this?

**Comment by dhruvdutt** [comment]
Seems fine. Amend all commits and make sure you follow the commit style guidelines.

**Comment by TechnicaVoyage** [comment]
@dhruvdutt Squashed all commits into one. 
By 
> follow the commit style guidelines

did you mean https://github.com/openMF/self-service-app/wiki/Commit-Style-Guide ? There is none given in this repo's wiki. I followed the fork and pull model from https://mifosforge.jira.com/wiki/spaces/MDZ/pages/92012609/How+to+contribute

**Comment by dhruvdutt** [comment]
Yes!

**Comment by TechnicaVoyage** [comment]
@dhruvdutt Please consider the pull request.

**Comment by botraunak** [comment]
@gauravsaini03 Already Fixed!

**Pull request closed without merging**
