### PR TITLE
Accounts UI added

### PR DESCRIPTION
**Pull request by botraunak**
- [x] Updated the Accounts screen to have loan, savings and share accounts
- [x] Fixed Datatable Issue, Sorting and pagination was not working in md-data-table.
- [x] Added a account status filter that shows the status of account in a color box. l

### CODE REVIEW

**Comment by botraunak** [comment]
@gauravsaini03  I have taken up the latest pull as you mentioned in the previous PR and tested it locally. The changes are tested from me. Thanks!

**Comment by gauravsaini03** [comment]
@kakoma Can you please verify this PR once at your end also.

**Comment by kakoma** [comment]
@gauravsaini03 Tested the changes. They look good. 
@botraunak We'll need to start adding some unit tests

**Comment by botraunak** [comment]
@kakoma Yes I do have worked on the unit testing setup as well. I'll send PRs after I get the features merged :+1:

**Pull request merged**
