### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by anweshknayak**

### CODE REVIEW

**Comment by anweshknayak** [comment]
@botraunak Please check this one :smile:  Minor readme fixes. Important for new contributors

**Comment by gauravsaini03** [comment]
@anweshknayak Can you check why the Travis build is failing ?

**Comment by anweshknayak** [comment]
@gauravsaini03 >The command "rake" exited with 1.

I think README.md should be excluded from Travis build?

**Comment by botraunak** [comment]
There is already a PR for develop branch for this readme Update closing this as duplicate

**Pull request closed without merging**
