### PR TITLE
Added Multi Language Support

### PR DESCRIPTION
**Pull request by botraunak**
Refactored all views for multi lang support

### CODE REVIEW

**Comment by vinaysaini** [comment]
@botraunak  We have a problem here. Either we need to add all the labels for the hindi language or we should show some default labels which are not present in the locale file.
Currently if we are selecting hindi language the complete UI after login is breaking.Check the screenshot.
image

**Comment by botraunak** [comment]
@vinaysaini It won't be possible to provide all the translations, the hindi one is an example on who we can create a locale file do it. I'm using the community app setup where the same thing happens if there isn't a key in the locale file it shows up like this. 
Also a default value I feel won't do any good in terms of usage purposes. But yes we can add a default value but everything in the development UI will start showing that string which will be strange. How should we resolve this? 
@gauravsaini03

**Comment by gauravsaini03** [comment]
@botraunak I think if we don't have all labels then we should discuss with @edcable regarding this and how we can get the translations. If we don't have the translations currently then I think we need to add only those labels that we have values, otherwise it end up messing up with the UI.

**Comment by gauravsaini03** [comment]
@botraunak Did you discussed with @edcable about this? What's your take regarding this, I think its a good feature for translation so we should not revert it but without all translations, I feel it will break the final product?

**Comment by botraunak** [comment]
Merging this will arise #38 The multi-language support needs to be fixed so that the ui doesn't break on the web app

**Comment by gauravsaini03** [comment]
For now I am merging this as for english it's working perfectly fine.

**Pull request merged**
