### PR TITLE
Updated account details

### PR DESCRIPTION
**Pull request by botraunak**
- Loan Account details updated
- Savings Account Details updated
- Added option to transfer and deposit in accounts

Added loan account details

Updated savings details

Updated loan account details for transactions and repayment schedule

added transfer to option in account

### CODE REVIEW

**Comment by gauravsaini03** [comment]
@vinaysaini Please code review this and test it at your end also.

**Comment by vinaysaini** [comment]
@gauravsaini03 I have reviewed and tested code at my end, seems to be working properly.

**Comment by gauravsaini03** [comment]
@botraunak After merging #57 looks like there are conflicts in this PR. Can you look into this.

**Comment by botraunak** [comment]
@gauravsaini03  Rebased and resolved and squashed :)

**Pull request merged**
